<?php namespace app\controllers\delegation;


class EmailMessenger extends AbstractMessenger
{
    /**
     * @return bool
     */
   public function send()
   {
       var_dump('Sent by' . __METHOD__);

       return parent::send(); // TODO: Change the autogenerated stub
   }
}